/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary': '#bdcab7',
        'surface-container-highest': '#333533',
        'surface-container': '#1e201e',
        'primary-container': '#386145',
        'surface-container-lowest': '#0d0f0d',
        'surface': '#121412',
        'on-background': '#e2e3df',
        'surface-tint': '#a4d1ae',
        'primary-fixed': '#bfeec9',
        'outline-variant': '#434843',
        'secondary': '#bccabd',
        'on-surface-variant': '#c3c8c1',
        'surface-variant': '#333533',
        'on-error': '#690005',
        'secondary-container': '#3f4c42',
        'outline': '#8d928c',
        'surface-container-low': '#1a1c1a',
        'tertiary-container': '#505c4c',
        'surface-dim': '#121412',
        'on-primary': '#0c381f',
        'surface-container-high': '#282a28',
        'on-surface': '#e2e3df',
        'primary': '#a4d1ae',
        'surface-bright': '#383a37',
        'primary-fixed-dim': '#a4d1ae',
        'on-primary-container': '#acdab6',
        'background': '#121412',
        'error-container': '#93000a',
        'error': '#ffb4ab',
        'inverse-surface': '#e2e3df',
        'inverse-on-surface': '#2f312f',
        'inverse-primary': '#3d674a',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Space Grotesk', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0px',
        'sm': '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-up': 'fadeUp 0.6s ease forwards',
        'fade-in': 'fadeIn 0.4s ease forwards',
        'slide-in': 'slideIn 0.5s ease forwards',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
};

